### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by mbcullen** [jamesacampbell/iptcinfo3#23]
I'm reading keywords from an image exported from Lightroom and I'm seeing a charset error, and the letter b is included before each element in the return. 

Here's my snippet of code: 

> from iptcinfo3 import IPTCInfo
> 
> def read_tags():
>     info = IPTCInfo('test2.jpg')
>     words = info['keywords']
>     print(words)

And this is the output: 

> WARNING: problems with charset recognition (b'\x1b')
> [b'cambodia', b'cow', b'overcast', b'temple']

This is the image that I'm running it on. 
![test2](https://user-images.githubusercontent.com/1843450/90923038-387ec900-e3aa-11ea-8efc-568cce445d83.jpg)

I can suppress the error, but is there a way to stop returning the extraneous b character?

**Comment by nealmcb** [comment]
This does look like an issue to me, and it shows up for a variety of folks as documented at https://stackoverflow.com/questions/50407738/python-disable-iptcinfo-warning

I think the code is parsing the value of `Iptc.Envelope.CharacterSet` wrong. The manner of specifying a character set that I see, and thta used in the example image here, is a string of control characters, e.g. the three characters `ESC % G` for UTF-8, as discussed at https://en.wikipedia.org/wiki/ISO/IEC_2022 and as documented in the standard: 

> 1:90 Coded Character Set
Optional, not repeatable, up to 32 octets, consisting of one or
more control functions used for the announcement, invocation or
designation of coded character sets. The control functions follow
the ISO 2022 standard and may consist of the escape control
character and one or more graphic characters. 

```
$ exiv2 -p a charset-example.jpg |egrep 'Iptc|Xmp'|cat -vt
Iptc.Envelope.ModelVersion                   Short       1  4
Iptc.Envelope.CharacterSet                   String      3  ^[%G
Iptc.Application2.RecordVersion              Short       1  4
Iptc.Application2.Caption                    String     16  a seller of eggs
Xmp.xmp.ModifyDate                           XmpText    25  2012-08-13T08:55:36-05:00
Xmp.xmp.CreatorTool                          XmpText    37  Windows Photo Editor 10.0.10011.16384
Xmp.dc.description                           LangAlt     1  lang="x-default" a seller of eggs
```

But iptcinfo3.py is trying to unpack the three characters as an `unsigned short` in network order (`!H`) and failing (perhaps because shorts are 2 characters?)

https://github.com/jamesacampbell/iptcinfo3/blob/a9cea6cb1981e4ad29cf317d44419e4fd45c2170/iptcinfo3.py#L802-L810

It then throws a confusing warning suggesting that the character set is `\x1b`, which is decimal 27. I initially went on a wild goose chase, finding character set 27 to not even be listed in the [IPTC Spec](https://www.iptc.org/std/IIM/4.1/specification/IIMV4.1.pdf) I looked at, though itis listed in the official list of [IANA Character Sets](https://www.iana.org/assignments/character-sets/character-sets.xhtml) where it is identified as *ISO-10646-UTF-1	27	Universal Transfer Format (1), this is the multibyte encoding, that subsets ASCII-7.*  But again, as far as I can see, the IPTC standard doesn't indicate character sets via simple binary numbers, but via old-school ISO 2022 escape sequences.

FWIW, the tool that created my metadata was `Xmp.xmp.CreatorTool: Windows Photo Editor 10.0.10011.16384`.
